name: Bump upstream version

on:
  schedule:
    - cron: "00 */4 * * *"
  push:
    branches:
      - "master"
jobs:
  bump-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: npx @dappnode/dappnodesdk github-action bump-upstream
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
